config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, to: "following#index"
        get :followers, to: "followers#index"
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(index show destroy)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to t(".title_link1"), Settings.footer.footer_link, target: :_blank %>
    <%= link_to t(".title_link2"), Settings.footer.footer_link2, target: :_blank %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), '#' %></li>
      <li><%= link_to t(".contact"), '#' %></li>
      <li><%= link_to t(".title_link3"), Settings.footer.footer_link3, target: :_blank %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample_app", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t(".home"), root_path %></li>
          <li><%= link_to t(".help"), help_path %></li>
          <% if logged_in? %>
            <li><%= link_to t(".user"), users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t(".profile"), current_user %></li>
                <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to t(".logout"), logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to t(".login"), login_path %></li>
          <% end %></li>
          <li><%= link_to t(".eng"), locale:"en" %></li>
          <li><%= link_to t(".vie"), locale:"vi" %></li>
        </ul>
      </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <script>
      var language = "<%= I18n.locale %>";
      I18n.translations = <%== I18n::JS.filtered_translations[I18n.locale].to_json %>;
    </script>
  </body>
</html>